FROM node:20-slim AS base
WORKDIR /snailycad

RUN apt-get update -y && apt-get install -y ca-certificates openssl
RUN npm install -g pnpm@9 && pnpm config set httpTimeout 1200000

COPY . .
RUN pnpm install --no-frozen-lockfile

ENV NODE_ENV="production"
RUN pnpm turbo run build --filter="{packages/*}"

WORKDIR /snailycad/apps/client
RUN rm -rf /snailycad/apps/client/.next
RUN pnpm create-images-domain

ARG NEXT_PUBLIC_CLIENT_URL
ARG NEXT_PUBLIC_PROD_ORIGIN
ENV NEXT_PUBLIC_CLIENT_URL=$NEXT_PUBLIC_CLIENT_URL
ENV NEXT_PUBLIC_PROD_ORIGIN=$NEXT_PUBLIC_PROD_ORIGIN

RUN pnpm run build
CMD ["sh", "-c", "HOSTNAME=0.0.0.0 pnpm start"]
